


(defpackage :clio-open
  (::use :cl :xlib :clue)
  (:export *default-contact-border*
	   *default-contact-foreground*
	   *default-display-bottom-margin*
	   *default-display-horizontal-space*
	   *default-display-left-margin*
	   *default-display-right-margin*
	   *default-display-text-font*
	   *default-display-top-margin*
	   *default-display-vertical-space*
	   *dialog-point-spacing*
	   ;; As good a place as any.
	   action-button
	   action-item
	   buffer
	   buffer-delete
	   buffer-insert
	   buffer-length
	   buffer-number-lines
	   buffer-subseq
	   button
	   button-dialog
	   button-font
	   button-label
	   button-label-alignment
	   button-switch
	   change-window-documentation
	   choice-default
	   choice-default
	   choice-font
	   choice-font
	   choice-item-font
	   choice-item-highlight-default-p
	   choice-item-highlight-selected-p
	   choice-item-label
	   choice-item-selected-p
	   choice-policy
	   choice-selection
	   choice-selection
	   choices
	   class-resources
	   command
	   command-area
	   command-control-area
	   command-default-accept
	   command-default-cancel
	   confirm
	   confirm-accept-label
	   confirm-accept-only
	   confirm-cancel-label
	   confirm-message
	   confirm-near
	   confirm-p
	   contact-border
	   contact-current-background
	   contact-current-background-pixel
	   contact-foreground
	   contact-scale
	   core
	   core-shell
	   default-resources ;; Debug aids
	   describe-resource
	   dialog
	   dialog-accept
	   dialog-button
	   dialog-cancel
	   dialog-default-control
	   dialog-item
	   display-bottom-margin
	   display-gravity
	   display-horizontal-space
	   display-image
	   display-image-source
	   display-left-margin
	   display-right-margin
	   display-text
	   display-text-alignment
	   display-text-copy
	   display-text-field
	   display-text-font
	   display-text-selection
	   display-text-source
	   display-top-margin
	   display-vertical-space
	   edit-text
	   edit-text-clear
	   edit-text-cut
	   edit-text-field
	   edit-text-field-length
	   edit-text-grow
	   edit-text-mark
	   edit-text-paste
	   edit-text-point
	   find-link
	   form
	   form-max-height
	   form-max-width
	   form-min-height
	   form-min-width
	   gravity
	   inch-pixels
	   link-attach-from
	   link-attach-to
	   link-from
	   link-length
	   link-maximum
	   link-minimum
	   link-orientation
	   link-to
	   link-update
	   make-action-button
	   make-action-item
	   make-choices
	   make-command
	   make-confirm
	   make-dialog-button
	   make-dialog-item
	   make-display-image
	   make-display-text
	   make-display-text-field
	   make-edit-text
	   make-edit-text-field
	   make-form
	   make-horizontal-link
	   make-menu
	   make-multiple-choices
	   make-property-sheet
	   make-scroll-frame
	   make-scroller
	   make-slider
	   make-table
	   make-text-command-table
	   make-toggle-button
	   make-vertical-link
	   mark
	   menu
	   menu-choice
	   menu-title
	   millimeter-pixels
	   move-mark
	   multiple-choices
	   pixel-inches
	   pixel-millimeters
	   pixel-points
	   pixel-round
	   point-pixels
	   present-dialog
	   property-sheet
	   property-sheet-area
	   rescale
	   scale-increment
	   scale-indicator-size
	   scale-maximum
	   scale-minimum
	   scale-orientation
	   scale-update
	   scale-update-delay
	   scale-value
	   scroll-frame
	   scroll-frame-area
	   scroll-frame-content
	   scroll-frame-horizontal
	   scroll-frame-left
	   scroll-frame-position
	   scroll-frame-reposition
	   scroll-frame-top
	   scroll-frame-vertical
	   scroller
	   slider
	   switch
	   table
	   table-column
	   table-column-alignment
	   table-column-width
	   table-columns
	   table-delete-policy
	   table-layout-size-policy
	   table-member
	   table-row
	   table-row-alignment
	   table-row-height
	   table-same-height-in-row
	   table-same-width-in-column
	   table-separator
	   text-command
	   text-command-table
	   toggle-button
	   window-documentation))

(defpackage :clio-example
  (::use :cl :xlib :clue :clio-open)
  (:export command-frame
	   command-frame-content
	   command-frame-controls
	   make-command-frame))
